### ISSUE TITLE
Use Zetier docker images

### ISSUE THREAD

**Issue by le91688** [Zetier/farmhand#16]
Switch to Zetier docker images for mypy and isort in `lint.yml`

```yml
jobs:
  mypy:
    runs-on: ubuntu-latest
    name: mypy
    steps:
    - uses: actions/checkout@v1
    - name: mypy
      uses: docker://le91688/dockerized_mypy:3.8-1.3.0 <---
      with:
        args: .

  isort:
    runs-on: ubuntu-latest
    name: isort
    steps:
    - uses: actions/checkout@v1
    - name: isort
      uses: docker://le91688/dockerized_isort:3.8-5.12.0 <---
      with:
        args: -c src/farmhand
```
